site_name: Recce Docs
site_description: >-
  Data change validation for dbt projects

copyright: Copyright &copy; 2025 Recce <br />

# Repository
repo_name: datarecce/recce
repo_url: https://github.com/datarecce/recce
site_url: https://docs.reccehq.com
extra_css:
  - styles/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HUUx9fyphJ
      name: Recce on Discord
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/datarecce
      name: Recce on X (Twitter)
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/datarecce.bsky.social
      name: Recce on Bluesky
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@DataRecce
      name: Recce on Mastadon
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datarecce
      name: Recce on LinkedIn
    - icon: fontawesome/brands/medium
      link: https://medium.com/inthepipeline
      name: Recce on Medium
    - icon: fontawesome/brands/github
      link: https://github.com/DataRecce/recce
      name: Recce on GitHub
    - icon: fontawesome/brands/slack
      link: https://getdbt.slack.com/archives/C05C28V7CPP
      name: Recce on Slack

nav:
  - Home: "https://reccehq.com/"
  - Guides:
      - What's Recce:
          - index.md
          - 1-whats-recce/community-support.md
          - Changelog: "https://blog.reccehq.com/tag/release"
      - Getting Started:
          - 2-getting-started/oss-vs-cloud.md
          - 2-getting-started/start-free-with-cloud.md
          #- 2-getting-started/cloud-5min-tutorial.md
          - 2-getting-started/installation.md
          - 2-getting-started/get-started-jaffle-shop.md
      - Visualized Change:
          - 3-visualized-change/lineage.md
          - 3-visualized-change/code-change.md
          - 3-visualized-change/column-level-lineage.md
          - 3-visualized-change/multi-models.md
      - Downstream Impacts:
          #- 4-downstream-impacts/metadata-first.md
          - 4-downstream-impacts/impact-radius.md
          - 4-downstream-impacts/breaking-change-analysis.md
          #- 4-downstream-impacts/transformation-types.md
      - Data Diffing:
          - 5-data-diffing/connect-to-warehouse.md
          - 5-data-diffing/row-count-diff.md
          - 5-data-diffing/profile-diff.md
          - 5-data-diffing/value-diff.md
          - 5-data-diffing/topK-diff.md
          - 5-data-diffing/histogram-diff.md
          - 5-data-diffing/query.md
      - Collaborate Validation:
          - 6-collaboration/invitation.md
          - 6-collaboration/checklist.md
          - 6-collaboration/share.md
      - CI/CD:
          # Brief intro explaining GitHub vs GitLab paths
          - 7-cicd/ci-cd-getting-started.md

          # GitHub CI/CD
          - Using GitHub:
              - 7-cicd/github/setup-ci.md
              #- 7-cicd/cloud-recce-summary.md
              #- 7-cicd/cloud-preset-checks.md
              - 7-cicd/github/scenario-ci.md
              - 7-cicd/github/setup-cd.md

          # GitLab CI/CD
          - Using GitLab:
              - 7-cicd/gitlab/setup-ci.md
              - 7-cicd/gitlab/setup-cd.md
              - 7-cicd/gitlab/gitlab-pat-guide.md

          #- 7-cicd/recce-debug.md # content outdated
          - 7-cicd/scenario-dev.md
          - 7-cicd/scenario-pr-review.md
          - 7-cicd/best-practices-prep-env.md
          #- 7-cicd/recce-summary.md content outdated
          - 7-cicd/preset-checks.md

      - Technical Concepts:
          - 8-technical-concepts/state-file.md
          - 8-technical-concepts/configuration.md

  - Blog: "https://blog.reccehq.com"
  - Start Free: "https://cloud.reccehq.com/"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        #- toc:
        #   title: On this page


  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  logo: assets/images/recce-logo-white.png
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: secondary
      primary: deep orange
      toggle:
        icon: material/brightness-4 # Icon to switch to dark mode
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: secondary-dark
      primary: deep orange
      toggle:
        icon: material/brightness-7 # Icon to switch back to light mode
        name: Switch to light mode

  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - glightbox:
      skip_classes:
        - skip-glightbox
  - social:
      cards_layout_options:
        background_color: "#2A6CA7"

watch:
  - docs
