site_name: Recce Docs
site_description: >-
  Data change validation for dbt projects

copyright: Copyright &copy; 2025 Recce <br />

# Repository
repo_name: datarecce/recce
repo_url: https://github.com/datarecce/recce
site_url: https://datarecce.io
extra_css:
  - styles/extra.css

extra:
  analytics:
    provider: google
    property: G-E06MSTE2SX
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HUUx9fyphJ
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/datarecce
    - icon: fontawesome/brands/bluesky
      link: https://x.com/datarecce
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@DataRecce
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datarecce
    - icon: fontawesome/brands/medium
      link: https://medium.com/inthepipeline
    - icon: fontawesome/brands/github
      link: https://github.com/DataRecce/recce
    - icon: fontawesome/brands/slack
      link: https://getdbt.slack.com/archives/C05C28V7CPP

nav:
  - Home: "https://datarecce.io/"
  - Guides:
      - Overview:
          - index.md
          - demo.md
      - Getting Started:
          - get-started.md
          - get-started-jaffle-shop.md
          - installation.md
          - start-with-dbt-cloud.md
      - Web UI:
          - features/lineage.md
          - features/query.md
          - features/checklist.md
      - Command Line Interface:
          - features/recce-run.md
          - features/recce-summary.md
      - Advanced Features:
          - features/state-file.md
          - features/preset-checks.md
          - features/node-selection.md
          - features/breaking-change-analysis.md
          - features/column-level-lineage.md
          - reference/configuration.md
      - Scenarios:
          - guides/scenario-dev.md
          - guides/scenario-pr-review.md
          - guides/scenario-ci.md
          - guides/best-practices-prep-env.md
      - Architecture:
          - architecture/overview.md
          - Changelog: "https://github.com/DataRecce/recce/releases"
      - Privacy & Terms:
          - agreement/privacy-policy.md
          - agreement/cookies-policy.md
          - agreement/terms-of-use.md
  - Cloud (Alpha):
      - recce-cloud/index.md
      - recce-cloud/getting-started-recce-cloud.md
      - recce-cloud/setup-gh-actions.md
      - recce-cloud/setup-gh-codespaces.md
      - recce-cloud/expose-recce-instance-visibility.md
      - recce-cloud/share-recce-session-securely.md
      - Cloud Architecture:
          # - recce-cloud/architecture/index.md
          - recce-cloud/architecture/security.md
  - Blog: "https://datarecce.io/blog"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        #- toc:
        #   title: On this page


  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  logo: assets/images/recce-logo-white.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-4 # Icon to switch to dark mode
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-7 # Icon to switch back to light mode
        name: Switch to light mode

  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - glightbox:
      skip_classes:
        - skip-glightbox
  - social:
      cards_layout_options:
        background_color: "#ff6e41"

watch:
  - docs
