site_name: Recce
site_description: >-
  Data change validation for dbt projects - 
  Create 'all signal, no noise' pull request comments

copyright: Copyright &copy; 2025 Recce <br /><a href="https://cal.com/team/recce/chat?utm_source=banner&utm_campaign=oss" target="_blank" /><img alt="Book us with Cal.com" src="https://cal.com/book-with-cal-light.svg" /></a>

# Repository
repo_name: datarecce/recce
repo_url: https://github.com/datarecce/recce
site_url: https://datarecce.io
extra_css:
  - styles/extra.css

extra:
  analytics:
    provider: google
    property: G-E06MSTE2SX
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HUUx9fyphJ
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/datarecce
    - icon: fontawesome/brands/bluesky
      link: https://x.com/datarecce
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@DataRecce
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datarecce
    - icon: fontawesome/brands/medium
      link: https://medium.com/inthepipeline
    - icon: fontawesome/brands/github
      link: https://github.com/DataRecce/recce
    - icon: fontawesome/brands/slack
      link: https://getdbt.slack.com/archives/C05C28V7CPP

nav:
  - index.md
  - Guides:
      - Overview:
          - index.md
          - demo.md
      - Getting Started:
          - get-started.md
          - get-started-jaffle-shop.md
          - installation.md
          - start-with-dbt-cloud.md
      - Web UI:
          - features/lineage.md
          - features/query.md
          - features/checklist.md
      - Command Line Interface:
          - features/recce-run.md
          - features/recce-summary.md
      - Advanced Features:
          - features/state-file.md
          - features/preset-checks.md
          - features/node-selection.md
          - features/breaking-change-analysis.md
          - features/column-level-lineage.md
          - reference/configuration.md
      - Scenarios:
          - guides/scenario-dev.md
          - guides/scenario-pr-review.md
          - guides/scenario-ci.md
          - guides/best-practices-prep-env.md
      - Architecture:
          - architecture/overview.md
      - Privacy & Terms:
          - agreement/privacy-policy.md
          - agreement/cookies-policy.md
          - agreement/terms-of-use.md
  - Cloud (Alpha):
      - recce-cloud/index.md
      - recce-cloud/getting-started-recce-cloud.md
      - recce-cloud/setup-gh-actions.md
      - recce-cloud/setup-gh-codespaces.md
      - recce-cloud/expose-recce-instance-visibility.md
      - recce-cloud/share-recce-session-securely.md
      - Cloud Architecture:
          # - recce-cloud/architecture/index.md
          - recce-cloud/architecture/security.md
  - Blog: "https://datarecce.io/blog"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        #- toc:
        #   title: On this page


  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true          

theme:
  name: material
  custom_dir: material/overrides
  logo: assets/images/recce-logo-white.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - tags:
      tags_file: blog/tags.md
  - glightbox:
      skip_classes:
        - skip-glightbox
  - social:
      cards_layout_options:
        background_color: "#ff6e41"
  - blog:
      blog_dir: blog
      archive: true
      post_dir: "{blog}/posts"
      categories_name: Categories
      post_url_format: "{slug}" # Removed date from URL "{date}/{slug}"
      blog_toc: false # enable for blog, archive and category index pages
      #archive_toc: false    # enable for archive index pages
      # categories_toc: true # enable for category index pages

watch:
  - material
