site_name: Recce Docs
site_description: >-
  Data change validation for dbt projects

copyright: Copyright &copy; 2025 Recce <br />

# Repository
repo_name: datarecce/recce
repo_url: https://github.com/datarecce/recce
site_url: https://docs.reccehq.com
extra_css:
  - styles/extra.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/HUUx9fyphJ
      name: Recce on Discord
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/datarecce
      name: Recce on X (Twitter)
    - icon: fontawesome/brands/bluesky
      link: https://x.com/datarecce
      name: Recce on Bluesky
    - icon: fontawesome/brands/mastodon
      link: https://mastodon.social/@DataRecce
      name: Recce on Mastadon
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/datarecce
      name: Recce on LinkedIn
    - icon: fontawesome/brands/medium
      link: https://medium.com/inthepipeline
      name: Recce on Medium
    - icon: fontawesome/brands/github
      link: https://github.com/DataRecce/recce
      name: Recce on GitHub
    - icon: fontawesome/brands/slack
      link: https://getdbt.slack.com/archives/C05C28V7CPP
      name: Recce on Slack

nav:
  - Home: "https://reccehq.com/"
  - Guides:
      - What's Recce:
          - 1-whats-recce/index.md
          - 1-whats-recce/community-support.md
          - Changelog: "https://blog.reccehq.com/tag/release"
      - Getting Started:
          - 2-getting-started/oss-vs-cloud.md
          - 2-getting-started/start-free-with-cloud.md
          - 2-getting-started/cloud-5min-tutorial.md
          - 2-getting-started/installation.md
          - 2-getting-started/get-started-jaffle-shop.md
      - View modified:
          - 3-view-modified/lineage.md
          - 3-view-modified/code-diff.md
          - 3-view-modified/column-level-lineage.md
      - Downstream impacts:
          - 4-downstream-impacts/metadata-first.md
          - 4-downstream-impacts/impact-radius.md
          - 4-downstream-impacts/breaking-change-analysis.md
          - 4-downstream-impacts/transformation-types.md
      - Data Diffing:
          - 5-data-diffing/row-count-diff.md  
          - 5-data-diffing/profile-diff.md
          - 5-data-diffing/value-diff.md
          - 5-data-diffing/topK-diff.md
          - 5-data-diffing/histogram-diff.md
          - 5-data-diffing/query.md
      - Collaborate Validation:
          - 6-collaboration/checklist.md
          - 6-collaboration/share-recce-session-securely.md
      - Workflow Integration:
          - 7-workflow-integration/automate-in-pr.md
          - 7-workflow-integration/setup-gh-actions.md
          - 7-workflow-integration/recce-summary.md
          - 7-workflow-integration/recce-summary-example.md
          - 7-workflow-integration/preset-checks.md
          - 7-workflow-integration/best-practices-prep-env.md
          - 7-workflow-integration/scenario-pr-review.md
        # Automate before PR
          - 7-workflow-integration/scenario-dev.md
        # CLI commands
          - 7-workflow-integration/recce-debug.md
          - 7-workflow-integration/recce-run.md
        # automate open source
          #  - 7-workflow-integration/scenario-ci.md
      - Lots models:
          - 8-lots-models/node-selection.md
      - Technical Concepts:
          - 9-technical-concepts/overview.md
          - 9-technical-concepts/state-file.md
          - 9-technical-concepts/configuration.md
          - 9-technical-concepts/security.md
  - Blog: "https://blog.reccehq.com"
  - Start Free: "https://cloud.reccehq.com/"

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        #- toc:
        #   title: On this page


  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

theme:
  name: material
  logo: assets/images/recce-logo-white.png
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-4 # Icon to switch to dark mode
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-7 # Icon to switch back to light mode
        name: Switch to light mode

  features:
    # - navigation.instant
    # - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - content.code.copy

plugins:
  - search
  - glightbox:
      skip_classes:
        - skip-glightbox
  - social:
      cards_layout_options:
        background_color: "#ff6e41"

watch:
  - docs
